const $=s=>document.querySelector(s),state={job:null,results:new Map(),selected:new Set(),timer:null};
$('#reference').addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const u=URL.createObjectURL(f);$('#preview').src=u;$('#referenceChip').src=u;$('#referenceName').textContent=f.name;$('#dropzone').classList.add('has-image')});
$('#changePhoto').onclick=e=>{e.preventDefault();$('#reference').click()};
$('#threshold').oninput=e=>{const v=+e.target.value,l=v<37?'Broad':v>51?'Strict':'Balanced';$('#thresholdValue').textContent=`${l} · ${v}%`};
$('#scanForm').onsubmit=async e=>{e.preventDefault();$('#formError').textContent='';const b=$('#scanButton');b.disabled=true;b.querySelector('span').textContent='Starting search…';const data=new FormData(e.target);data.set('threshold',(+$('#threshold').value/100).toFixed(2));try{const r=await fetch('/api/scan',{method:'POST',body:data}),j=await r.json();if(!r.ok)throw Error(j.error||'Could not start scan.');state.job=j.id;$('#setupView').classList.add('hidden');$('#resultsView').classList.remove('hidden');scrollTo({top:0});poll()}catch(x){$('#formError').textContent=x.message;b.disabled=false;b.querySelector('span').textContent='Find matching photos'}};
async function poll(){try{const r=await fetch(`/api/jobs/${state.job}`),j=await r.json();if(!r.ok)throw Error(j.error||'Search lost.');progress(j);render(j.matches);if(j.status==='complete'){$('#statusText').textContent=`Reviewed ${j.total.toLocaleString()} photos in ${j.elapsed}s.`;$('#progressCard').classList.add('hidden');$('#emptyState').classList.toggle('hidden',j.matches.length>0);return}if(j.status==='error')throw Error(j.error);state.timer=setTimeout(poll,650)}catch(x){$('#progressTitle').textContent='Search stopped';$('#currentFile').textContent=x.message;$('#currentFile').style.color='#ffaaa3'}}
function progress(j){const p=j.total?j.processed/j.total*100:2;$('#progressBar').style.width=p+'%';$('#progressNumbers').textContent=j.total?`${j.processed.toLocaleString()} / ${j.total.toLocaleString()}`:'Getting ready';$('#progressTitle').textContent=j.status==='preparing'?'Preparing face recognition…':'Scanning your photo folder…';$('#currentFile').textContent=j.current||'The first run downloads the recognition models.';$('#matchCount').textContent=j.matches.length;$('#statusText').textContent=j.status==='scanning'?`${j.processed.toLocaleString()} photos checked so far`:'Preparing private on-device scan'}
function render(items){for(const x of items){if(state.results.has(x.id))continue;state.results.set(x.id,x);const c=document.createElement('article');c.className='photo-card';c.dataset.id=x.id;c.innerHTML=`<img src="/api/jobs/${state.job}/images/${x.id}" alt="${esc(x.name)}" loading="lazy"><span class="check"></span><span class="face-box"></span><div class="meta"><span><strong>${esc(x.name)}</strong><small>${esc(x.relative)}</small></span><b class="score">${x.score}%</b></div>`;c.onclick=()=>toggle(x.id);c.querySelector('img').onload=e=>box(c,e.target,x.box);$('#gallery').append(c)}}
function box(c,img,b){const s=Math.max(c.clientWidth/img.naturalWidth,c.clientHeight/img.naturalHeight),cx=(img.naturalWidth*s-c.clientWidth)/2,cy=(img.naturalHeight*s-c.clientHeight)/2,f=c.querySelector('.face-box');f.style.cssText=`left:${b[0]*s-cx}px;top:${b[1]*s-cy}px;width:${b[2]*s}px;height:${b[3]*s}px`}
function toggle(id,on=!state.selected.has(id)){on?state.selected.add(id):state.selected.delete(id);const c=document.querySelector(`[data-id="${id}"]`);if(c){c.classList.toggle('selected',on);c.querySelector('.check').textContent=on?'✓':''}selection()}
function selection(){const n=state.selected.size;$('#selectedCount').textContent=n;$('#copyButton').disabled=$('#deleteButton').disabled=!n;$('#selectAll').checked=n>0&&n===state.results.size;$('#selectAll').indeterminate=n>0&&n<state.results.size}
$('#selectAll').onchange=e=>state.results.forEach((_,id)=>toggle(id,e.target.checked));$('#copyButton').onclick=()=>$('#copyDialog').showModal();$('#deleteButton').onclick=()=>$('#deleteDialog').showModal();
$('#copyForm').onsubmit=async e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();const destination=$('#destination').value.trim();if(!destination)return;await mutate('copy',{ids:[...state.selected],destination});$('#copyDialog').close()};
$('#confirmDelete').onclick=async e=>{e.preventDefault();const j=await mutate('delete',{ids:[...state.selected],confirmation:'DELETE'});if(j){j.deleted.forEach(id=>{document.querySelector(`[data-id="${id}"]`)?.remove();state.results.delete(id);state.selected.delete(id)});$('#matchCount').textContent=state.results.size;selection();$('#deleteDialog').close()}};
async function mutate(action,payload){try{const r=await fetch(`/api/jobs/${state.job}/${action}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),j=await r.json();if(!r.ok)throw Error(j.error||'Action failed.');toast(j.message);return j}catch(x){toast(x.message);return null}}
$('#newSearch').onclick=()=>{clearTimeout(state.timer);location.reload()};function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),3500)}function esc(t){const d=document.createElement('div');d.textContent=t;return d.innerHTML}
